DROP DATABASE IF EXISTS popquizDB;

CREATE DATABASE popquizDB;

USE popquizDB;

CREATE TABLE quiz (
  id INT NOT NULL AUTO_INCREMENT,
  quiz VARCHAR(45) NULL,
  ex01 VARCHAR(45) NULL,
  ex02 VARCHAR(45) NULL,
  ex03 VARCHAR(45) NULL,
  PRIMARY KEY (id)
);